version: "3.8"
services:

    # PHP service
    app:
        build: .
        container_name: php-8
        working_dir: /var/www/html/
        volumes:
            - ./:/var/www/html/
        networks:
            - php8-network

    # MySQL database service
    db:
        image: mysql:5.7.13
        # command: mysqld --default-authentication-plugin=mysql_native_password
        # restart: unless-stopped
        container_name: php8db
        ports:
            - 3390:3306
        expose:
            - 3306
        environment:
            MYSQL_ROOT_PASSWORD: 'php123'
            # MYSQL_DATABASE: 'php_8_db'
            # MYSQL_USER: 'php8user'
            # MYSQL_PASSWORD: 'php123'
        volumes:
          - ./mysql:/var/lib/mysql
        networks:
            - php8-network

    # Nginx service
    nginx:
        image: nginx:alpine
        container_name: php8-nginx
        ports:
            - 8001:80
            - 8002:81
            - 8003:82
        expose:
            - 80
        volumes:
            - ./:/var/www/html/
            - ./nginx/:/etc/nginx/conf.d/
        networks:
            - php8-network
networks:
    php8-network:
        driver: bridge
# volumes:
#     mysql:
#         driver: local
